Alderbrook_Town_MapScripts::
	.byte 0


Alderbrook_Town_MapScripts_PathSign::
# 4 "data/maps/Alderbrook_Town/scripts.pory"
	msgbox Alderbrook_Town_MapScripts_PathSign_Text_0, MSGBOX_SIGN
	end


Alderbrook_Town_MapScripts_LabSign::
# 9 "data/maps/Alderbrook_Town/scripts.pory"
	msgbox Alderbrook_Town_MapScripts_LabSign_Text_0, MSGBOX_SIGN
	end


Alderbrook_Town_MapScripts_PathSign_Text_0:
# 4 "data/maps/Alderbrook_Town/scripts.pory"
	.string "<- Alderbrook Town\nRoute 1 ->$"

Alderbrook_Town_MapScripts_LabSign_Text_0:
# 9 "data/maps/Alderbrook_Town/scripts.pory"
	.string "Alderbrook Pokemon Research Lab\nProfessor Larch's Lab$"
