Weirford_MapScripts::
	.byte 0


Weirford_MapScripts_GreetingsSign::
# 4 "data/maps/Weirford/scripts.pory"
	msgbox Weirford_MapScripts_GreetingsSign_Text_0, MSGBOX_SIGN
	return


Weirford_MapScripts_GymSign::
# 8 "data/maps/Weirford/scripts.pory"
	msgbox Weirford_MapScripts_GymSign_Text_0, MSGBOX_SIGN
	return


Weirford_MapScripts_MartNPC::
# 12 "data/maps/Weirford/scripts.pory"
	msgbox Weirford_MapScripts_MartNPC_Text_0, MSGBOX_DEFAULT
	return


Weirford_MapScripts_GardenNPC::
# 16 "data/maps/Weirford/scripts.pory"
	msgbox Weirford_MapScripts_GardenNPC_Text_0, MSGBOX_DEFAULT
	return


Weirford_MapScripts_GreetingsSign_Text_0:
# 4 "data/maps/Weirford/scripts.pory"
	.string "Welcome to Weirford!$"

Weirford_MapScripts_GymSign_Text_0:
# 8 "data/maps/Weirford/scripts.pory"
	.string "Down the alley if you're\nlooking for a scrap!$"

Weirford_MapScripts_MartNPC_Text_0:
# 12 "data/maps/Weirford/scripts.pory"
	.string "Have you been inside that scary looking building yet?$"

Weirford_MapScripts_GardenNPC_Text_0:
# 16 "data/maps/Weirford/scripts.pory"
	.string "A bit of greenery in a town is\nalways welcome.$"
