Weirford_Forest_MapScripts::
	.byte 0


Weirford_Forest_MapScripts_BugCatcherSam::
# 4 "data/maps/Weirford_Forest/scripts.pory"
	trainerbattle_single TRAINER_WEIRFORDFOREST_BUGCATCHER_SAM, Weirford_Forest_MapScripts_BugCatcherSam_TrainerPreBattle, Weirford_Forest_MapScripts_BugCatcherSam_TrainerDefeated, Weirford_Forest_MapScripts_BugCatcherSam_Beaten
# 10 "data/maps/Weirford_Forest/scripts.pory"
	msgbox Weirford_Forest_MapScripts_BugCatcherSam_TrainerPostBattle, MSGBOX_AUTOCLOSE
	end


Weirford_Forest_MapScripts_CamperColin::
# 15 "data/maps/Weirford_Forest/scripts.pory"
	trainerbattle_single TRAINER_WEIRFORDFOREST_CAMPER_COLIN, Weirford_Forest_MapScripts_CamperColin_TrainerPreBattle, Weirford_Forest_MapScripts_CamperColin_TrainerDefeated, Weirford_Forest_MapScripts_CamperColin_Beaten
# 21 "data/maps/Weirford_Forest/scripts.pory"
	msgbox Weirford_Forest_MapScripts_CamperColin_TrainerPostBattle, MSGBOX_AUTOCLOSE
	end


Weirford_Forest_MapScripts_BugCatcherJason::
# 26 "data/maps/Weirford_Forest/scripts.pory"
	trainerbattle_single TRAINER_WEIRFORDFOREST_BUGCATCHER_JASON, Weirford_Forest_MapScripts_BugCatcherJason_TrainerPreBattle, Weirford_Forest_MapScripts_BugCatcherJason_TrainerDefeated, Weirford_Forest_MapScripts_BugCatcherJason_Beaten
# 32 "data/maps/Weirford_Forest/scripts.pory"
	msgbox Weirford_Forest_MapScripts_BugCatcherJason_TrainerPostBattle, MSGBOX_AUTOCLOSE
	end


Weirford_Forest_MapScripts_CorpoEric::
# 37 "data/maps/Weirford_Forest/scripts.pory"
	trainerbattle_single TRAINER_WEIRFORDFOREST_CORPO_ERIC, Weirford_Forest_MapScripts_CorpoEric_TrainerPreBattle, Weirford_Forest_MapScripts_CorpoEric_TrainerDefeated, Weirford_Forest_MapScripts_CorpoEric_Beaten
# 43 "data/maps/Weirford_Forest/scripts.pory"
	msgbox Weirford_Forest_MapScripts_CorpoEric_TrainerPostBattle, MSGBOX_AUTOCLOSE
	end


Weirford_Forest_MapScripts_LassLila::
# 48 "data/maps/Weirford_Forest/scripts.pory"
	trainerbattle_single TRAINER_WEIRFORDFOREST_LASS_LILA, Weirford_Forest_MapScripts_LassLila_TrainerPreBattle, Weirford_Forest_MapScripts_LassLila_TrainerDefeated, Weirford_Forest_MapScripts_LassLila_Beaten
# 54 "data/maps/Weirford_Forest/scripts.pory"
	msgbox Weirford_Forest_MapScripts_LassLila_TrainerPostBattle, MSGBOX_AUTOCLOSE
	end


Weirford_Forest_MapScripts_CorpoEric_TrainerPreBattle::
# 58 "data/maps/Weirford_Forest/scripts.pory"
	.string "Corpo Eric wants to battle!$"

Weirford_Forest_MapScripts_CorpoEric_TrainerPostBattle::
# 62 "data/maps/Weirford_Forest/scripts.pory"
	.string "Corpo Eric: Thanks for the battle!$"

Weirford_Forest_MapScripts_CorpoEric_TrainerDefeated::
# 66 "data/maps/Weirford_Forest/scripts.pory"
	.string "Corpo Eric: I can't believe I lost!$"

Weirford_Forest_MapScripts_CorpoEric_Beaten::
# 70 "data/maps/Weirford_Forest/scripts.pory"
	.string "Corpo Eric has been defeated!$"

Weirford_Forest_MapScripts_LassLila_TrainerPreBattle::
# 74 "data/maps/Weirford_Forest/scripts.pory"
	.string "Lass Lila wants to battle!$"

Weirford_Forest_MapScripts_LassLila_TrainerPostBattle::
# 78 "data/maps/Weirford_Forest/scripts.pory"
	.string "Lass Lila: Thanks for the battle!$"

Weirford_Forest_MapScripts_LassLila_TrainerDefeated::
# 82 "data/maps/Weirford_Forest/scripts.pory"
	.string "Lass Lila: I can't believe I lost!$"

Weirford_Forest_MapScripts_LassLila_Beaten::
# 86 "data/maps/Weirford_Forest/scripts.pory"
	.string "Lass Lila has been defeated!$"

Weirford_Forest_MapScripts_BugCatcherJason_TrainerPreBattle::
# 90 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Jason wants to battle!$"

Weirford_Forest_MapScripts_BugCatcherJason_TrainerPostBattle::
# 94 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Jason: Thanks for the battle!$"

Weirford_Forest_MapScripts_BugCatcherJason_TrainerDefeated::
# 98 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Jason: I can't believe I lost!$"

Weirford_Forest_MapScripts_BugCatcherJason_Beaten::
# 102 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Jason has been defeated!$"

Weirford_Forest_MapScripts_CamperColin_TrainerPreBattle::
# 106 "data/maps/Weirford_Forest/scripts.pory"
	.string "Camper Colin wants to battle!$"

Weirford_Forest_MapScripts_CamperColin_TrainerPostBattle::
# 110 "data/maps/Weirford_Forest/scripts.pory"
	.string "Camper Colin: Thanks for the battle!$"

Weirford_Forest_MapScripts_CamperColin_TrainerDefeated::
# 114 "data/maps/Weirford_Forest/scripts.pory"
	.string "Camper Colin: I can't believe I lost!$"

Weirford_Forest_MapScripts_CamperColin_Beaten::
# 118 "data/maps/Weirford_Forest/scripts.pory"
	.string "Camper Colin has been defeated!$"

Weirford_Forest_MapScripts_BugCatcherSam_TrainerPreBattle::
# 122 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Sam wants to battle!$"

Weirford_Forest_MapScripts_BugCatcherSam_TrainerPostBattle::
# 126 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Sam: Thanks for the battle!$"

Weirford_Forest_MapScripts_BugCatcherSam_TrainerDefeated::
# 130 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Sam: I can't believe I lost!$"

Weirford_Forest_MapScripts_BugCatcherSam_Beaten::
# 134 "data/maps/Weirford_Forest/scripts.pory"
	.string "Bug Catcher Sam has been defeated!$"
