Westlock_Village_MapScripts::
	.byte 0


Westlock_Village_EventScript_MainSign::
# 5 "data/maps/Westlock_Village/scripts.pory"
	msgbox Westlock_Village_EventScript_MainSign_Text_0, MSGBOX_SIGN
	end


Westlock_Village_EventScript_LibrarySign::
# 11 "data/maps/Westlock_Village/scripts.pory"
	msgbox Westlock_Village_EventScript_LibrarySign_Text_0, MSGBOX_SIGN
	end


Westlock_Village_EventScript_MainSign_Text_0:
# 5 "data/maps/Westlock_Village/scripts.pory"
	.string "Welcome to Westlock Village!$"

Westlock_Village_EventScript_LibrarySign_Text_0:
# 11 "data/maps/Westlock_Village/scripts.pory"
	.string "Westlock Library\nRoute 2 ->$"
